---
title: "AI_05_データの前処理"
format: html
---

# CSVファイルからデータを読み込む

```{python}
# 必要なライブラリのimport
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
```

```{python}
# CSVファイルの読み込み
dataset = pd.read_csv("../Lesson05_Data-Preprocessing/baseball_salary.csv")
```

```{python}
# datasetの型を確認
type(dataset)
```

# データを理解しよう

```{python}
# 最初の5行を表示
dataset.head()
```

```{python}
# データの形状を確認
dataset.shape
```

```{python}
# 全体的な情報を表示
dataset.info()
```

```{python}
# 行番号を確認
dataset.index.values
```

```{python}
# 列ラベルを確認
dataset.columns.values
```

```{python}
# 行番号は数値型
print(type(dataset.index.values[0]))
# 列ラベルは文字型
print(type(dataset.columns.values[0]))

```

```{python}
# 列の方を確認する別の方法
dataset.dtypes
```

```{python}
# 列を指定して型を確認
dataset['推定年俸'].dtype
```

## 要約統計量の表示

```{python}
# 要約統計量を表示
dataset.describe()
```

## 基本的なデータ操作

### iloc

行列を番号で指定。第一引数で行、第二引数で列を指定する。\
引数には数値やスライス、リストを指定可。

```{python}
# データを抜き出す
# 0行目から4行目、3列目から5列目までをilocで抜き出す
dataset.iloc[:5, 3:6]
```

### loc

行を index で、列を columns で指定。\
locではスライスの終点を含まないが、**locの場合は終わりの要素を含んで指定**するので注意。

```{python}
# 0行目から4行目、3列目から5列目までをlocで抜き出す
dataset.loc[:4, '年数':'身長']
```

### 列名や行番号を指定

列名はリストによる複数の指定が可能。スライスとの組み合わせも可。

```{python}
# 0行目から4行目、3列目から5列目までを列名や行番号の指定で抜き出す
dataset[['年数','年齢','身長']][:5]
```

### フィルタリング

```{python}
# '年数'が10以上 かつ 打率が3割以上
dataset.query("年数 >= 10 and 打率 >= 0.3").head()
```

# データの可視化

```{python}
# 日本語を使わないデータフレームを作成
dataset2 = dataset[['球団','推定年俸', '打率']]
dataset2 = dataset2.rename(columns={'球団': 'team', '推定年俸': 'salary', '打率': 'batting_avg'})
dataset2 .head()
```

## ヒストグラム

```{python}
tmp = dataset2['salary'].hist(bins=20)

plt.show()
```

## 散布図

```{python}
tmp = dataset2.plot(kind = 'scatter', x = 'salary', y = 'batting_avg')

plt.show()
```

## 棒グラフ

```{python}
# 球団ごとの推定年俸(平均）を salary_by_team に格納
salary_by_team = dataset2[['team','salary']].groupby('team').mean().reset_index()

# 棒グラフを表示
tmp = salary_by_team.plot.bar(x='team')

plt.show()
```

## 箱ひげ図

```{python}
# 棒グラフで確認した推定年俸上位３チームである球団 g, h, l の「team, salary」を抜き出し
top3_team = dataset2.query("team in ['g', 'h', 'l']")[['team', 'salary']]

# teamごとのsalaryをboxplotで表示
ax = top3_team.boxplot(by = 'team')
# Boxplot ... の下のタイトル表示を抑制
ax.set_title('')

plt.show()
```

# 機械学習に向けたデータの準備

## 列の演算

```{python}
# 安打の中で本塁打の割合
dataset["本塁打率"] = dataset["本塁打"] / dataset["安打"]
dataset["本塁打率"].head()

```

```{python}
# 推定年俸の対数
dataset['推定年俸の対数'] = np.log10(dataset['推定年俸'])
dataset['推定年俸の対数'].head()
```

```{python}
# 元のdatasetに新たな列が追加されていることを確認
dataset.head()
```

## カテゴリーデータの扱い（カテゴリー変数）

分析のためにカテゴリー名のカラムに変換し、その値を 1 か 0 にする。\
この列を**カテゴリー変数**または**ダミー変数**と呼ぶ。\
カテゴリー変数を作成するには get_dummies() 関数が利用できる。

```{python}
# 球団が削除され、代わりに球団のカテゴリー変数が作成されたDataFrameが返る
dataset3 = pd.get_dummies(data = dataset, columns = ['球団'])
dataset3.head()
```

### 正規化

```{python}
# 正規化用にdatasetの一部を抜き出し
dataset4 = dataset[["推定年俸", "打点"]]
dataset4.head()
```

#### z-score normalization

平均値0、標準偏差1に変換します。標準化（Standardization）とも呼ばれます。正規分布にしたがっているデータは主にこちらを使用します。計算式は `（値 - 平均値）／標準偏差` となります。

```{python}
# z-score normalization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
dataset4_std = sc.fit_transform(dataset4)
```

#### Min-Max Normalization

最小値0、最大値1に変換します。最小値と最大値が決まっていて、データが一様分布の場合はこちらを使用します。計算式は `（値 - 最小値）／（最大値 - 最小値）` となります。

```{python}
# Min-Max Normalization
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler () 
dataset4_norm = ms.fit_transform(dataset4)
```

### 欠損値の扱い

isnullで列ごとの欠損値有無を確認\
sumで行数を合計

```{python}
# 欠損地の数の確認
dataset.isnull().sum()
```

欠損値をなんらかの値で補完するには `fillna` 関数を使用

```{python}
# 欠損値のある行の例1
dataset.iloc[4, 0:5]
```

```{python}
# 欠損値に平均値を代入。dataset['年数'].mean() で平均値を求めている
dataset['年数'] = dataset['年数'].fillna(dataset['年数'].mean())
dataset.iloc[4, 0:5]
```

欠損値を含む行を削除するには `dropna` 関数を使用

```{python}
# 欠損値のある行の例2
dataset.iloc[3, 5:10]
```

```{python}
# 欠損値を含む行を削除
dataset = dataset.dropna()
dataset.iloc[3, 5:10]
```
### 次元削減
#### 列同士の相関を確認
```{python}
# 列同士の相関を確認
dataset.corr(numeric_only = True)
```

```{python}
# 説明用のDataframe作成
dataset2 = dataset[['推定年俸', '打率', '出塁率']]
dataset2 = dataset2.rename(columns={'推定年俸': 'salary', '打率': 'batting_avg', '出塁率': 'on_base_per'})
```


```{python}
# 打率と出塁率の相関性の確認
tmp = dataset2.plot(kind = 'scatter', x='batting_avg', y='on_base_per')
plt.show()
```
```{python}
# 推定年俸の打率の相関性の確認
tmp = dataset2.plot(kind = 'scatter', x='salary', y='batting_avg')
plt.show()
```

```{python}
# 推定年俸と出塁率の相関性の確認
tmp = dataset2.plot(kind = 'scatter', x='salary', y='on_base_per')
plt.show()
```

#### 主成分分析（Principal Component Analysis, PCA）による次元削減
```{python}
from sklearn.decomposition import PCA

# batting_avgとon_base_perを取り出して主成分分析（1つの成分にまとめる）
pca = PCA(n_components=1).fit(dataset2[['batting_avg', 'on_base_per']])

# 主成分分析した結果を基にデータ変換を行い成分を取得する
values = pca.transform(dataset2[['batting_avg', 'on_base_per']])

# 得られた成分をdataset2に追加
dataset2['PCA_val'] = values[:,0]
```

```{python}
# 推定年俸とPCA成分の相関性の確認
tmp = dataset2.plot(kind = 'scatter', x='salary', y='PCA_val')
plt.show()
```




