---
title: "回帰モデル"
format: html
jupyter: python3
---

```{python}
# 必要なライブラリのimport
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# seabornの装飾を適用する
sns.set_theme
```

# データ読込

```{python}
# Irisのデータセットの読み込み
from sklearn.datasets import load_iris
iris = load_iris()
```

irisデータセットは辞書形式なので `keys()` を使って構成確認する

```{python}
# irisの構成
iris.keys()
```

```{python}
# DESCR:データの説明
print(iris['DESCR'])
```

```{python}
# data:説明変数
print(iris['data'].shape)
print(type(iris['data']))
print(iris['data'])
```

```{python}
# feature_names:説明変数の列名
iris['feature_names']
```

```{python}
# target:目的変数
print(iris['target'].shape)
print(type(iris['target']))
print(iris['target'])
```

```{python}
# target_names:目的変数の値に対応する名称
iris['target_names']
```

以降の処理で使うデータセットの作成

```{python}
# irisのfeature_namesは「sepal length(cm)」 のように空白やカッコが付いていて扱いづらいので以下の列名を使用する
feature_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

# datasetの作成
dataset = pd.DataFrame(data = iris['data'], columns = feature_names)
dataset['species'] = iris['target']
dataset.head()
```

```{python}
sns.pairplot(dataset, hue='species', diag_kind= 'hist')
plt.show()
```

# パーセプトロン

パーセプトロンは、複数の**入力**を受け取り、1つの値を**出力**する機械学習のモデルの一種。

## 二値分類

```{python}
# 「setosaかそれ以外か」の列
is_setosa = (dataset['species'] == 0).astype(np.int64)

# datasetに追加
dataset['is_setosa'] = is_setosa
dataset.head()
```

```{python}
# setosaとそれ以外で分類した散布図
sns.lmplot(
  x = 'petal_width', y = 'petal_length',
  hue = 'is_setosa',
  data = dataset,
  fit_reg = False
)
plt.show()
```

```{python}
# 必要なライブラリの追加読み込み
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
```

```{python}
# 目的変数（Y）：is_setosa、説明変数（X）：petal_widthとpetal_length
Y = np.array(dataset['is_setosa'])
X = np.array(dataset[['petal_width', 'petal_length']])
```

```{python}
# 形状を確認
print("Y=", Y.shape, ", X=", X.shape)
```

```{python}
# データの分割
X_train, X_test, Y_train, Y_test = train_test_split(
  X, Y,
  test_size=0.3, random_state=0
)
X_train, X_valid, Y_train, Y_valid = train_test_split(
  X_train, Y_train,
  test_size=0.3, random_state=0
)
```

```{python}
perceptron_model = Perceptron()
perceptron_model.fit(X_train, Y_train)
Y_pred = perceptron_model.predict(X_valid)
```

```{python}
# 正解（検証データの目的変数）と予測値との比較
print(Y_valid[:5])
print(Y_pred[:5])
```

### モデルの確認

パーセプトロンは線形なので、重みは線形回帰モデルと同様にして取得可能。

```{python}
w0 = perceptron_model.intercept_[0]
w1 = perceptron_model.coef_[0][0]
w2 = perceptron_model.coef_[0][1]

print("w0:", w0, ", w1:", w1, ", w2:", w2)
```

散布図に直線で表現すると、

$$
w_0 + w_1 x_1 + w_2 x_2 = 0
$$

つまり

$$
x_2 = \frac{w_0 + w_1 x_1}{- w_2}
$$

※ここで言うx2はY軸方向の値

```{python}
# モデルの式
x1 = np.linspace(0, 3, 10)
x2 = (2 - 1.2 * x1) / 0.7　
# perceptron_modelで得た切片と係数

plt.figure()
# 実際の値（setosa以外）
data = dataset.query("is_setosa == 0")
plt.scatter(data['petal_width'],data['petal_length'], color = "blue", label = 0)

# 実際の値（setosa)
data = dataset.query("is_setosa == 1")
plt.scatter(data['petal_width'],data['petal_length'], color = "orange", label = 1)

# モデルの式（setosaの部分）
plt.plot(x1, x2, color = "green", linewidth = 2)
plt.fill_between(x1, x2,color = "green", linewidth = 0, alpha = .05)

# グラフ全体の大きさを指定
plt.xlim(0, 2.8)
plt.ylim(0, 7.5)

# 凡例の表示
plt.legend(loc = "upper left", title = "is_setosa")

plt.show()
```

### モデルの評価

分類モデルの場合「どのぐらい正解しているか」が評価基準となる。

#### 正解率

「全体のなかで正解したものの割合」

```{python}
# 正解率
from sklearn.metrics import accuracy_score
accuracy_score(Y_valid, Y_pred)
```

#### 適合率

「正解と判断した中で真に正解の割合」

```{python}
# 適合率
from sklearn.metrics import precision_score
precision_score(Y_valid, Y_pred)
```

#### 再現率

「真に正解のうち正解と判断した割合」

```{python}
# 再現率
from sklearn.metrics import recall_score
recall_score(Y_valid, Y_pred)
```

#### F1値

適合率と再現率の調和平均（逆数の平均を求め、それを逆数にした値）

```{python}
# F1値
from sklearn.metrics import f1_score
f1_score(Y_valid, Y_pred)
```

#### まとめて出力

```{python}
# モデルの評価をまとめて出力
from sklearn.metrics import classification_report
print(classification_report(Y_valid, Y_pred))
```

# ロジスティック回帰

「1か0」ではなく「setosaである確率」を出力する

## シグモイド関数

※下記 $exp(-ax)$ は $e^{-ax}$ のこと

$$
y = \frac{1}{1 + \exp(-ax)}
$$

```{python}
from sklearn.linear_model import LogisticRegression
```

```{python}
# ロジスティック回帰のモデルを作成し、学習して予測
logistic_model = LogisticRegression()
logistic_model.fit(X_train, Y_train)
Y_pred = logistic_model.predict(X_valid)

# モデルの評価
print(classification_report(Y_valid, Y_pred))
```

## 多クラス分類

```{python}
# Y:目的変数、X:説明変数
Y = np.array(dataset['species'])
X = np.array(dataset[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']])
```

```{python}
# データの分割
X_train, X_test, Y_train, Y_test = train_test_split(
  X, Y,
  test_size=0.3, random_state=0
)
X_train, X_valid, Y_train, Y_valid = train_test_split(
  X_train, Y_train,
  test_size=0.3, random_state=0
)
```

```{python}
# ロジスティック回帰（多クラス分類）のモデルを作成し、学習して予測
logistic_model = LogisticRegression()
logistic_model.fit(X_train, Y_train)
Y_pred = logistic_model.predict(X_valid)

# モデルの評価
print(classification_report(Y_valid, Y_pred))
```

# 決定木とランダムフォレスト

## 決定木

決定木は直線では分類が難しいようなデータに向いているが、どこまでもデータを分割できるので、過学習が起こりやすいと言われている。よって以下のようなパラメータをチューニングして、最適なモデルを構築する。

-   木の深さ
-   リーフの数
-   ノードを分割するために必要なデータの数
-   リーフを構成するために必要なデータの数

```{python}
# 必要なライブラリの追加読み込み
from sklearn.tree import DecisionTreeClassifier
```

データはロジスティック回帰で作成したものを利用

```{python}
# 決定木のモデルを作成し、学習して予測
tree_model = DecisionTreeClassifier(criterion = 'entropy')
tree_model.fit(X_train, Y_train)
Y_pred = tree_model.predict(X_valid)

# モデルの評価
print(classification_report(Y_valid, Y_pred))
```

精度があまり高くないため、パラメータのチューニングのためグリッドSearchを使う

```{python}
# グリッドサーチを使う
from sklearn.model_selection import GridSearchCV

# モデル:決定木
model = DecisionTreeClassifier()

# max_depth:木の深さ, min_samples_split:ノードを分割するために必要なデータの数
params = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [5, 10, 50],
    'min_samples_split': [2, 4, 10]
}

# グリッドサーチ
gscv = GridSearchCV(model, param_grid = params, cv = 3)

# データの分割:機械学習用データを学習と検証に分けるのはクロスバリデーションで行ってくれる
Xg_train, Xg_test, Yg_train, Yg_test = train_test_split(
  X, Y,
  test_size = 0.3, random_state = 0
)

gscv.fit(Xg_train, Yg_train)
```

```{python}
# 最適なパラメータ
gscv.best_params_
```

最適なパラメータを元に構築し直す\
※テキストだと以下の結果になっていて、そちらの方が性能がいい。なぜ。

```         
'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 10
```

```{python}
# 最適なパラメータによる決定木のモデル作成と学習、予測
tree_model = DecisionTreeClassifier(
  criterion = 'gini',
  max_depth = 5,
  min_samples_split = 2
)
tree_model.fit(X_train, Y_train)
Y_pred = tree_model.predict(X_valid)

# モデルの評価
print(classification_report(Y_valid, Y_pred))
```

## ランダムフォレスト

複数の決定木を組み合わせて予測性能を高くしたモデル

```{python}
# 必要なライブラリの追加読み込み
from sklearn.ensemble import RandomForestClassifier
```

```{python}
# ランダムフォレストのモデルを作成し、学習して予測
randomforest_model = RandomForestClassifier(n_estimators = 100)
randomforest_model.fit(X_train, Y_train)
Y_pred = randomforest_model.predict(X_valid)

# モデルの評価
print(classification_report(Y_valid, Y_pred))
```

グリッドサーチで最適なパラメータを探る

```{python}
# グリッドサーチを使う
# モデル：ランダムフォレスト
model = RandomForestClassifier()

# max_depth:木の深さ, min_samples_split:ノードを分割するために必要なデータの数
params = {
    'n_estimators': [10, 50, 100],
    'max_depth': [5, 10, 50]
}

# グリッドサーチ
gscv = GridSearchCV(model, param_grid = params, cv = 3)

# データの分割:機械学習用データを学習と検証に分けるのはクロスバリデーションで行ってくれる
Xg_train, Xg_test, Yg_train, Yg_test = train_test_split(
  X, Y,
  test_size = 0.3, random_state = 0
)

gscv.fit(Xg_train, Yg_train)
```

```{python}
# 最適なパラメータ
gscv.best_params_
```

```{python}
# 最適なパラメータによるランダムフォレストのモデル作成と学習、予測
randomforest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5)
randomforest_model.fit(X_train, Y_train)
Y_pred = randomforest_model.predict(X_valid)

# モデルの評価
print(classification_report(Y_valid, Y_pred))
```

# サポートベクターマシーン（SVM）

SVMとは、マージンを最大化するようにデータを分割する境界線を決定するモデル。分割線を決めるのに重要なのは分割線から近いデータであり、このデータをサポートベクトルと呼ぶ。

```{python}
# 必要なライブラリの追加読み込み
from sklearn.svm import SVC
```

```{python}
# SVMのモデルを作成し、学習して予測
svm_model = SVC()
svm_model.fit(X_train, Y_train)
Y_pred = svm_model.predict(X_valid)

# モデルの評価
print(classification_report(Y_valid, Y_pred))
```

テストデータによる汎化性能の評価

```{python}
# テストデータによる評価
Y_pred = svm_model.predict(X_test)

# モデルの評価
print(classification_report(Y_test, Y_pred))
```
